name: nick
age : 26
password: 3353113843
#等价于header :order
header: '{cipher}37bea5a546562727d0d21c1ab2b832733e9faf804b38321d2f4e47cc7d92a082'
# header: order

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka/

spring: 
  datasource:
    jdbc-url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=utf-8
    driverClassName: com.mysql.jdbc.Driver
    username: springCloud
    password: cclss
    